Class {
	#name : 'PannShellfishCohort',
	#superclass : 'CMAgent',
	#instVars : [
		'age',
		'size',
		'numberOfShellfish'
	],
	#category : 'FemmesEtCoquillages-Model',
	#package : 'FemmesEtCoquillages-Model'
}

{ #category : 'accessing' }
PannShellfishCohort >> age [

	^ age
]

{ #category : 'accessing' }
PannShellfishCohort >> age: anObject [

	age := anObject
]

{ #category : 'accessing' }
PannShellfishCohort >> numberOfShellfish [

	^ numberOfShellfish
]

{ #category : 'accessing' }
PannShellfishCohort >> numberOfShellfish: anObject [

	numberOfShellfish := anObject
]

{ #category : 'accessing' }
PannShellfishCohort >> size [

	^ size
]

{ #category : 'accessing' }
PannShellfishCohort >> size: anObject [

	size := anObject
]
